require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CustomerSegmentsController do

  # This should return the minimal set of attributes required to create a valid
  # CustomerSegment. As you add validations to CustomerSegment, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "title" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CustomerSegmentsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all customer_segments as @customer_segments" do
      customer_segment = CustomerSegment.create! valid_attributes
      get :index, {}, valid_session
      assigns(:customer_segments).should eq([customer_segment])
    end
  end

  describe "GET show" do
    it "assigns the requested customer_segment as @customer_segment" do
      customer_segment = CustomerSegment.create! valid_attributes
      get :show, {:id => customer_segment.to_param}, valid_session
      assigns(:customer_segment).should eq(customer_segment)
    end
  end

  describe "GET new" do
    it "assigns a new customer_segment as @customer_segment" do
      get :new, {}, valid_session
      assigns(:customer_segment).should be_a_new(CustomerSegment)
    end
  end

  describe "GET edit" do
    it "assigns the requested customer_segment as @customer_segment" do
      customer_segment = CustomerSegment.create! valid_attributes
      get :edit, {:id => customer_segment.to_param}, valid_session
      assigns(:customer_segment).should eq(customer_segment)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CustomerSegment" do
        expect {
          post :create, {:customer_segment => valid_attributes}, valid_session
        }.to change(CustomerSegment, :count).by(1)
      end

      it "assigns a newly created customer_segment as @customer_segment" do
        post :create, {:customer_segment => valid_attributes}, valid_session
        assigns(:customer_segment).should be_a(CustomerSegment)
        assigns(:customer_segment).should be_persisted
      end

      it "redirects to the created customer_segment" do
        post :create, {:customer_segment => valid_attributes}, valid_session
        response.should redirect_to(CustomerSegment.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved customer_segment as @customer_segment" do
        # Trigger the behavior that occurs when invalid params are submitted
        CustomerSegment.any_instance.stub(:save).and_return(false)
        post :create, {:customer_segment => { "title" => "invalid value" }}, valid_session
        assigns(:customer_segment).should be_a_new(CustomerSegment)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        CustomerSegment.any_instance.stub(:save).and_return(false)
        post :create, {:customer_segment => { "title" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested customer_segment" do
        customer_segment = CustomerSegment.create! valid_attributes
        # Assuming there are no other customer_segments in the database, this
        # specifies that the CustomerSegment created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        CustomerSegment.any_instance.should_receive(:update_attributes).with({ "title" => "MyString" })
        put :update, {:id => customer_segment.to_param, :customer_segment => { "title" => "MyString" }}, valid_session
      end

      it "assigns the requested customer_segment as @customer_segment" do
        customer_segment = CustomerSegment.create! valid_attributes
        put :update, {:id => customer_segment.to_param, :customer_segment => valid_attributes}, valid_session
        assigns(:customer_segment).should eq(customer_segment)
      end

      it "redirects to the customer_segment" do
        customer_segment = CustomerSegment.create! valid_attributes
        put :update, {:id => customer_segment.to_param, :customer_segment => valid_attributes}, valid_session
        response.should redirect_to(customer_segment)
      end
    end

    describe "with invalid params" do
      it "assigns the customer_segment as @customer_segment" do
        customer_segment = CustomerSegment.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CustomerSegment.any_instance.stub(:save).and_return(false)
        put :update, {:id => customer_segment.to_param, :customer_segment => { "title" => "invalid value" }}, valid_session
        assigns(:customer_segment).should eq(customer_segment)
      end

      it "re-renders the 'edit' template" do
        customer_segment = CustomerSegment.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CustomerSegment.any_instance.stub(:save).and_return(false)
        put :update, {:id => customer_segment.to_param, :customer_segment => { "title" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested customer_segment" do
      customer_segment = CustomerSegment.create! valid_attributes
      expect {
        delete :destroy, {:id => customer_segment.to_param}, valid_session
      }.to change(CustomerSegment, :count).by(-1)
    end

    it "redirects to the customer_segments list" do
      customer_segment = CustomerSegment.create! valid_attributes
      delete :destroy, {:id => customer_segment.to_param}, valid_session
      response.should redirect_to(customer_segments_url)
    end
  end

end
