require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe UvpsController do

  # This should return the minimal set of attributes required to create a valid
  # Uvp. As you add validations to Uvp, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "title" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # UvpsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all uvps as @uvps" do
      uvp = Uvp.create! valid_attributes
      get :index, {}, valid_session
      assigns(:uvps).should eq([uvp])
    end
  end

  describe "GET show" do
    it "assigns the requested uvp as @uvp" do
      uvp = Uvp.create! valid_attributes
      get :show, {:id => uvp.to_param}, valid_session
      assigns(:uvp).should eq(uvp)
    end
  end

  describe "GET new" do
    it "assigns a new uvp as @uvp" do
      get :new, {}, valid_session
      assigns(:uvp).should be_a_new(Uvp)
    end
  end

  describe "GET edit" do
    it "assigns the requested uvp as @uvp" do
      uvp = Uvp.create! valid_attributes
      get :edit, {:id => uvp.to_param}, valid_session
      assigns(:uvp).should eq(uvp)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Uvp" do
        expect {
          post :create, {:uvp => valid_attributes}, valid_session
        }.to change(Uvp, :count).by(1)
      end

      it "assigns a newly created uvp as @uvp" do
        post :create, {:uvp => valid_attributes}, valid_session
        assigns(:uvp).should be_a(Uvp)
        assigns(:uvp).should be_persisted
      end

      it "redirects to the created uvp" do
        post :create, {:uvp => valid_attributes}, valid_session
        response.should redirect_to(Uvp.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved uvp as @uvp" do
        # Trigger the behavior that occurs when invalid params are submitted
        Uvp.any_instance.stub(:save).and_return(false)
        post :create, {:uvp => { "title" => "invalid value" }}, valid_session
        assigns(:uvp).should be_a_new(Uvp)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Uvp.any_instance.stub(:save).and_return(false)
        post :create, {:uvp => { "title" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested uvp" do
        uvp = Uvp.create! valid_attributes
        # Assuming there are no other uvps in the database, this
        # specifies that the Uvp created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Uvp.any_instance.should_receive(:update_attributes).with({ "title" => "MyString" })
        put :update, {:id => uvp.to_param, :uvp => { "title" => "MyString" }}, valid_session
      end

      it "assigns the requested uvp as @uvp" do
        uvp = Uvp.create! valid_attributes
        put :update, {:id => uvp.to_param, :uvp => valid_attributes}, valid_session
        assigns(:uvp).should eq(uvp)
      end

      it "redirects to the uvp" do
        uvp = Uvp.create! valid_attributes
        put :update, {:id => uvp.to_param, :uvp => valid_attributes}, valid_session
        response.should redirect_to(uvp)
      end
    end

    describe "with invalid params" do
      it "assigns the uvp as @uvp" do
        uvp = Uvp.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Uvp.any_instance.stub(:save).and_return(false)
        put :update, {:id => uvp.to_param, :uvp => { "title" => "invalid value" }}, valid_session
        assigns(:uvp).should eq(uvp)
      end

      it "re-renders the 'edit' template" do
        uvp = Uvp.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Uvp.any_instance.stub(:save).and_return(false)
        put :update, {:id => uvp.to_param, :uvp => { "title" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested uvp" do
      uvp = Uvp.create! valid_attributes
      expect {
        delete :destroy, {:id => uvp.to_param}, valid_session
      }.to change(Uvp, :count).by(-1)
    end

    it "redirects to the uvps list" do
      uvp = Uvp.create! valid_attributes
      delete :destroy, {:id => uvp.to_param}, valid_session
      response.should redirect_to(uvps_url)
    end
  end

end
